<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>$title$</title>
    <link rel="stylesheet" href="$base$/static/css/ui.datepicker.css" type="text/css"/>
    <link rel="stylesheet" href="$base$/static/css/main.css" type="text/css"/>
    <script type="text/javascript" src="$base$/static/js/jquery-1.2.6.js"></script>
    <script type="text/javascript" src="$base$/static/js/ui.datepicker.js"></script>
    $head;format="none"$
</head>
<body class='$page.properties.("body.class")$'>
<div id="content">
    <h1>$title$</h1>
    $body;format="none"$
</div>
</body>
</html>
