<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
  "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>$title$</title>
    <link rel="stylesheet" href="$base$/static/theme/jquery-ui-1.8.custom.css" type="text/css">
    <link rel="stylesheet" href="$base$/static/css/main.css?$request.version$" type="text/css">
    <script type="text/javascript" src="$base$/static/js/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="$base$/static/js/jquery-ui-1.8.custom.min.js"></script>
    <script type="text/javascript" src="$base$/static/js/buttons.js?$request.version$"></script>
    $head;format="none"$
</head>
<body class='$page.properties.("body.class")$'>
<div id="container">
    <div id="header">
        <h1>$title$</h1>
    </div>
    <div id="content">
        $body;format="none"$
    </div>
</div>
</body>
</html>
