<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>$title$</title>
    <link rel="stylesheet" href="$base$/static/css/reset.css" type="text/css"/>
    <link rel="stylesheet" href="$base$/static/theme/jquery-ui-1.8.custom.css" type="text/css"/>
    <link rel="stylesheet" href="$base$/static/css/main.css" type="text/css"/>
    <script type="text/javascript" src="$base$/static/js/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="$base$/static/js/jquery-ui-1.8.custom.min.js"></script>
    <script type="text/javascript" src="$base$/static/js/buttons.js"></script>
    $head;format="none"$
</head>
<body class='$page.properties.("body.class")$'>
<div id="container">
    <div id="header">
        <h1>$title$</h1>
    </div>
    <div id="content">
        $body;format="none"$
    </div>
</div>
</body>
</html>
