<html>
<head>
    <title>Success</title>
</head>
<body>
<p>
    You submitted:<br />
    $document.one.value$<br />
    $document.two.value$<br />
    $document.date.value$<br />
</p>
<p>
    Click <a href="$oldFormLink$">here</a> to go back to the form.
</p>
<p>
    Click <a href="$newFormLink$">here</a> to start again.
</p>
<p>
    Click <a href="$indexLink$">here</a> to go to the list of forms.
</p>
</body>
</html>
